name: Update GitHub profile README
on:
  schedule:
    - cron: "12 6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          repository: nfrankel/nfrankel
          path: nfrankel
          token:  ${{ secrets.NFRANKEL_GITHUB_TOKEN }}
      - name: Install dependencies via Poetry
        run: poetry install
      - name: Update README
        run: poetry run python src/main.py --live
      - name: Commit README and push
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './nfrankel'
          add: README.adoc
          default_author: github_actions
          message: Automatically update README.adoc
